from __future__ import annotations

import re
from collections import Counter

from .contracts import (
    ScanAnalystJobInput,
    ScanAnalystManagedServerInput,
    ScanAnalystRequest,
    ScanAnalystResponse,
    ScanAnalystRuleInput,
    ScanAnalystRuleResponse,
    ScanAnalystPlanProposalResponse,
    ScanAnalystScannerCapability,
    ScanAnalystTargetResponse,
)

_TOKEN_RE = re.compile(r"[a-z0-9]{3,}")
_SCANNER_KEYWORDS: dict[ScanAnalystScannerCapability, tuple[str, ...]] = {
    "Yara": ("yara", "file", "files", "binary", "malware", "artifact", "hash"),
    "Sigma": ("sigma", "windows", "event", "events", "log", "logs", "powershell", "evtx"),
    "Snort": ("snort", "network", "traffic", "packet", "packets", "pcap", "beacon"),
    "Suricata": ("suricata", "network", "traffic", "packet", "packets", "pcap", "http"),
}


def recommend_scan_plan(request: ScanAnalystRequest) -> ScanAnalystResponse:
    selected_scanner = request.preferred_scanner_capability or _choose_scanner(request)
    selected_targets, target_warnings = _choose_targets(request, selected_scanner)
    selected_rules, rule_selection_mode, rule_scope_type, rule_scope_value, rule_warnings = _choose_rules(
        request,
        selected_scanner,
    )

    focus_label = request.focus_subnet.name if request.focus_subnet else "server inventory"
    plan_name = _build_plan_name(request.objective, selected_scanner, focus_label)
    description = (
        f"AI analyst proposal for {focus_label}. Objective: {request.objective.strip()}"
    )
    operator_notes = (
        f"Generated by the AI scan analyst from discovery, inventory, and recent execution posture. "
        f"Focus: {focus_label}. Objective: {request.objective.strip()}"
    )

    observations = _build_observations(request, selected_scanner, selected_targets, selected_rules)
    reasoning = _build_reasoning(request, selected_scanner, selected_targets, selected_rules, rule_selection_mode)
    validation_warnings = [*target_warnings, *rule_warnings]

    proposal = ScanAnalystPlanProposalResponse(
        name=plan_name,
        description=description,
        scanner_capability=selected_scanner,
        rule_selection_mode=rule_selection_mode,
        rule_scope_type=rule_scope_type,
        rule_scope_value=rule_scope_value,
        cadence_type="Manual",
        operator_notes=operator_notes,
        status="Draft",
        target_server_ids=[item.target_server_id for item in selected_targets],
        rule_revision_ids=[item.rule_revision_id for item in selected_rules],
        targets=selected_targets,
        rules=selected_rules,
    )

    return ScanAnalystResponse(
        summary=(
            f"Prepared a {selected_scanner} scan proposal for {len(selected_targets)} target"
            f"{'' if len(selected_targets) == 1 else 's'} with "
            f"{'explicit rules' if rule_selection_mode == 'RuleSet' else 'scope-based rule selection'}."
        ),
        observations=observations,
        reasoning=reasoning,
        validation_warnings=validation_warnings,
        recommended_scanner_capability=selected_scanner,
        proposal=proposal,
    )


def _choose_scanner(request: ScanAnalystRequest) -> ScanAnalystScannerCapability:
    objective = request.objective.lower()
    scores: Counter[str] = Counter()
    for scanner, keywords in _SCANNER_KEYWORDS.items():
        for keyword in keywords:
            if keyword in objective:
                scores[scanner] += 3

    for server in request.managed_servers:
        capabilities = {item.lower() for item in server.scanner_capabilities}
        for scanner in ("Yara", "Sigma", "Snort", "Suricata"):
            if scanner.lower() in capabilities:
                scores[scanner] += 1

        os_label = server.operating_system.lower()
        if "windows" in os_label:
            scores["Sigma"] += 1
        if "linux" in os_label or "server" in os_label:
            scores["Yara"] += 1

    return max(("Yara", "Sigma", "Snort", "Suricata"), key=lambda scanner: (scores[scanner], -list(_SCANNER_KEYWORDS).index(scanner)))


def _choose_targets(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
) -> tuple[list[ScanAnalystTargetResponse], list[str]]:
    ranked: list[tuple[float, ScanAnalystManagedServerInput]] = []
    warnings: list[str] = []
    objective = request.objective.lower()

    for server in request.managed_servers:
        score = 0.0
        if request.focus_subnet and server.subnet_id == request.focus_subnet.subnet_id:
            score += 4
        if server.connectivity_status.lower() == "online":
            score += 3
        elif server.connectivity_status.lower() == "degraded":
            score += 1.5
        if server.status.lower() == "active":
            score += 2
        if scanner.lower() in {item.lower() for item in server.scanner_capabilities}:
            score += 2.5
        if server.environment and server.environment.lower() in objective:
            score += 1.5
        if server.hostname.lower() in objective or server.ip_address in objective:
            score += 3
        if "windows" in objective and "windows" in server.operating_system.lower():
            score += 2
        if "linux" in objective and "linux" in server.operating_system.lower():
            score += 2
        ranked.append((score, server))

    ranked.sort(key=lambda item: (item[0], item[1].hostname.lower()), reverse=True)
    selected = [
        server
        for score, server in ranked[: request.max_target_count]
        if score > 0 or len(ranked) <= request.max_target_count
    ]
    if not selected:
        selected = [item for _, item in ranked[: request.max_target_count]]

    output: list[ScanAnalystTargetResponse] = []
    for server in selected:
        reason_bits: list[str] = []
        if request.focus_subnet and server.subnet_id == request.focus_subnet.subnet_id:
            reason_bits.append("belongs to the focused subnet")
        if server.connectivity_status.lower() == "online":
            reason_bits.append("currently online")
        if scanner.lower() in {item.lower() for item in server.scanner_capabilities}:
            reason_bits.append(f"already advertises {scanner} coverage")
        elif server.scanner_capabilities:
            warnings.append(
                f"{server.hostname} does not currently advertise {scanner}; the plan may rely on connector fallback."
            )
        if not reason_bits:
            reason_bits.append("ranked as the best available analyst candidate")
        output.append(
            ScanAnalystTargetResponse(
                target_server_id=server.target_server_id,
                hostname=server.hostname,
                ip_address=server.ip_address,
                operating_system=server.operating_system,
                environment=server.environment,
                status=server.status,
                connectivity_status=server.connectivity_status,
                scanner_capabilities=server.scanner_capabilities,
                reason=", ".join(reason_bits),
            )
        )

    return output, list(dict.fromkeys(warnings))


def _choose_rules(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
) -> tuple[list[ScanAnalystRuleResponse], str, str | None, str | None, list[str]]:
    candidate_rules = [rule for rule in request.candidate_rules if rule.rule_family.lower() == scanner.lower()]
    warnings: list[str] = []
    if not candidate_rules:
        return [], "RuleScope", "Global", None, [f"No active {scanner} rules were available; using scope-based selection."]

    tokens = set(_TOKEN_RE.findall(request.objective.lower()))
    ranked: list[tuple[float, ScanAnalystRuleInput]] = []
    for rule in candidate_rules:
        searchable = " ".join(
            filter(
                None,
                [
                    rule.rule_name,
                    rule.description,
                    rule.scope_type,
                    rule.scope_value or "",
                    rule.lifecycle_status,
                ],
            )
        ).lower()
        overlap = len(tokens.intersection(_TOKEN_RE.findall(searchable)))
        score = float(overlap * 3 + rule.revision_number)
        if request.focus_subnet and rule.scope_type.lower() == "subnet" and rule.scope_value == request.focus_subnet.subnet_id:
            score += 2
        ranked.append((score, rule))

    ranked.sort(key=lambda item: (item[0], item[1].revision_number, item[1].rule_name.lower()), reverse=True)
    selected_rows = [rule for score, rule in ranked[:5] if score > 0]

    if not selected_rows:
        scope_type = "Subnet" if request.focus_subnet else "Global"
        scope_value = request.focus_subnet.subnet_id if request.focus_subnet else None
        warnings.append("No high-signal rule matches were found in the objective text; using scope-based selection.")
        return [], "RuleScope", scope_type, scope_value, warnings

    return (
        [
            ScanAnalystRuleResponse(
                rule_revision_id=rule.rule_revision_id,
                rule_artifact_id=rule.rule_artifact_id,
                rule_name=rule.rule_name,
                rule_family=rule.rule_family,
                revision_number=rule.revision_number,
                version_label=rule.version_label,
                lifecycle_status=rule.lifecycle_status,
                scope_type=rule.scope_type,
                scope_value=rule.scope_value,
                reason="matched objective keywords and is the current active revision",
            )
            for rule in selected_rows
        ],
        "RuleSet",
        None,
        None,
        warnings,
    )


def _build_observations(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
    targets: list[ScanAnalystTargetResponse],
    rules: list[ScanAnalystRuleResponse],
) -> list[str]:
    observations = [
        f"Evaluated {len(request.discovery_runs)} discovery runs, {len(request.discovered_hosts)} discovered hosts, and {len(request.managed_servers)} managed servers.",
        f"Selected {scanner} based on the objective wording and available scanner coverage.",
        f"Prepared {len(targets)} target candidate{'s' if len(targets) != 1 else ''} and {len(rules)} explicit rule candidate{'s' if len(rules) != 1 else ''}.",
    ]
    if request.recent_jobs:
        latest_job = request.recent_jobs[0]
        observations.append(
            f"Most recent observed job status was {latest_job.status} with {latest_job.detection_count} detections."
        )
    return observations


def _build_reasoning(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
    targets: list[ScanAnalystTargetResponse],
    rules: list[ScanAnalystRuleResponse],
    rule_selection_mode: str,
) -> list[str]:
    reasoning = [
        f"{scanner} is the best fit for the requested objective given the available context.",
        "Targets were prioritized by subnet focus, live connectivity, active status, and scanner alignment.",
    ]
    if rule_selection_mode == "RuleSet":
        reasoning.append("A compact RuleSet was chosen so the analyst can review exactly which rules will run.")
    else:
        reasoning.append("RuleScope mode was chosen because the objective was broader than the current explicit rule matches.")
    if request.focus_subnet:
        reasoning.append(f"The proposal is anchored to subnet {request.focus_subnet.name} ({request.focus_subnet.cidr_block}).")
    if targets and any(not target.scanner_capabilities for target in targets):
        reasoning.append("Some selected targets have limited advertised scanner coverage, so fallback execution paths may be required.")
    if not rules:
        reasoning.append("The proposal intentionally avoids hard-coding rule revisions until better keyword alignment is available.")
    return reasoning


def _build_plan_name(objective: str, scanner: ScanAnalystScannerCapability, focus_label: str) -> str:
    tokens = _TOKEN_RE.findall(objective.lower())
    objective_label = "-".join(tokens[:4]) or "analyst-objective"
    focus = re.sub(r"[^a-z0-9]+", "-", focus_label.lower()).strip("-") or "fleet"
    return f"{scanner.lower()}-{focus}-{objective_label}"[:96]
