using System.Net.Http.Json;
using System.Text.Json;
using Backend.Application.Abstractions.Integrations;
using Backend.Application.Common;
using Backend.Infrastructure.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Backend.Infrastructure.Integrations;

public sealed class AiAdjudicationClient : IAiAdjudicationClient
{
    private const string SidecarDependencyName = "ai_sidecar";
    private const string TemporaryUnavailableCondition = "temporarily_unavailable";
    private const string SafeUnavailableMessage = "AI sidecar is temporarily unavailable. Retry later.";

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private readonly HttpClient _httpClient;
    private readonly AiSidecarOptions _options;
    private readonly ILogger<AiAdjudicationClient> _logger;

    public AiAdjudicationClient(
        HttpClient httpClient,
        IOptions<AiSidecarOptions> options,
        ILogger<AiAdjudicationClient> logger)
    {
        _httpClient = httpClient;
        _options = options.Value;
        _logger = logger;
    }

    public async Task<AiScoreCaseResult> ScoreCaseAsync(AiScoreCaseRequest request, CancellationToken cancellationToken)
    {
        var payload = BuildScorePayload(request);
        var root = await PostForJsonAsync(_options.ScoreCasePath, payload, cancellationToken);

        var decisionNode = TryGetProperty(root, out var nested, "groundedDecision", "grounded_decision")
            ? nested
            : root;

        var evidenceSources = ParseEvidenceSources(decisionNode);
        var provenance = ParseProvenance(decisionNode);
        var scoredAtUtc = TryReadTimestamp(root, out var scoredAt)
            ? scoredAt
            : DateTimeOffset.UtcNow;

        return new AiScoreCaseResult(
            Verdict: ReadRequiredString(decisionNode, "verdict"),
            Action: ReadRequiredString(decisionNode, "action"),
            Confidence: ReadRequiredDecimal(decisionNode, "confidence"),
            FalsePositiveRisk: ReadRequiredDecimal(decisionNode, "falsePositiveRisk", "false_positive_risk"),
            ReviewPriority: ReadRequiredString(decisionNode, "reviewPriority", "review_priority"),
            ShouldPromoteToIndicator: ReadRequiredBoolean(decisionNode, "shouldPromoteToIndicator", "should_promote_to_indicator"),
            ShouldSuppress: ReadRequiredBoolean(decisionNode, "shouldSuppress", "should_suppress"),
            ShouldAllowlist: ReadRequiredBoolean(decisionNode, "shouldAllowlist", "should_allowlist"),
            ShouldEscalate: ReadRequiredBoolean(decisionNode, "shouldEscalate", "should_escalate"),
            Reasons: ReadStringArray(decisionNode, "reasons"),
            Provenance: provenance,
            NextBestEvidence: ReadStringArray(decisionNode, "nextBestEvidence", "next_best_evidence"),
            AbstainReason: ReadOptionalString(decisionNode, "abstainReason", "abstain_reason"),
            ModelVersion: ReadOptionalString(root, "modelVersion", "model_version"),
            DatasetVersion: ReadOptionalString(root, "datasetVersion", "dataset_version"),
            ScoredAtUtc: scoredAtUtc,
            EvidenceSources: evidenceSources,
            RawPayload: root.Clone());
    }

    public async Task<AiExplainCaseResult> ExplainCaseAsync(AiExplainCaseRequest request, CancellationToken cancellationToken)
    {
        var payload = new
        {
            @case = new
            {
                id = request.CaseId,
                title = $"Case {request.CaseId}",
                summary = "Automated adjudication replay context",
                ownerUserId = "system-ai-adjudication",
                state = "open",
                openedAtUtc = request.DecidedAtUtc,
                closedAtUtc = (DateTimeOffset?)null,
            },
            decision = new
            {
                id = request.DecisionId,
                decisionState = request.DecisionState,
                recommendationCode = request.RecommendationCode,
                recommendationSummary = "Generated by adjudication worker",
                snapshotHash = request.SnapshotHash,
                modelVersion = request.ModelVersion,
                policyVersion = request.PolicyVersion,
                transformationLineageHash = request.TransformationLineageHash,
                decidedAtUtc = request.DecidedAtUtc,
            },
            snapshot = new
            {
                id = request.SnapshotHash,
                snapshotHash = request.SnapshotHash,
                capturedAtUtc = request.DecidedAtUtc,
                featureWindowStartUtc = request.DecidedAtUtc.AddHours(-24),
                featureWindowEndUtc = request.DecidedAtUtc,
                capturedByPipeline = "backend-ai-adjudication",
            },
            evidenceReferences = request.Provenance.Select((item, index) => new
            {
                evidenceAssertionId = item.EvidenceId ?? $"prov-{index}",
                evidenceReference = item.CitationRef ?? item.Key,
                assertionType = item.Source,
                statement = item.Value,
                confidence = 0.7m,
                isConflicting = false,
                sourceReference = item.Source,
                observedAtUtc = request.DecidedAtUtc,
                referencedAtUtc = request.DecidedAtUtc,
            }).ToArray(),
            transformationLineage = Array.Empty<object>(),
            graphArtifacts = Array.Empty<object>(),
            featureVectors = Array.Empty<object>(),
            graphDerivedFeatures = Array.Empty<object>(),
            assetCriticalityValues = Array.Empty<object>(),
            sourceTrustValues = Array.Empty<object>(),
            policyVersionRefs = Array.Empty<object>(),
            modelVersionRefs = Array.Empty<object>(),
        };

        var root = await PostForJsonAsync(_options.ExplainCasePath, payload, cancellationToken);
        var generatedAt = TryReadTimestamp(root, out var timestamp)
            ? timestamp
            : DateTimeOffset.UtcNow;

        return new AiExplainCaseResult(
            Summary: ReadRequiredString(root, "explanationSummary", "explanation_summary"),
            DecisionState: ReadRequiredString(root, "decisionState", "decision_state"),
            RecommendedAction: ReadRequiredString(root, "recommendedAction", "recommended_action"),
            Rationale: ReadStringArray(root, "rationale"),
            Citations: ParseExplainCitations(root),
            NextBestEvidence: ReadStringArray(root, "nextBestEvidence", "next_best_evidence"),
            PolicyVersion: ReadOptionalString(root, "policyVersion", "policy_version"),
            ModelVersion: ReadOptionalString(root, "modelVersion", "model_version"),
            DatasetVersion: ReadOptionalString(root, "datasetVersion", "dataset_version"),
            GeneratedAtUtc: generatedAt,
            RawPayload: root.Clone());
    }

    public async Task<AiRecommendActionResult> RecommendActionAsync(AiScoreCaseRequest request, CancellationToken cancellationToken)
    {
        var payload = BuildScorePayload(request);
        var root = await PostForJsonAsync(_options.RecommendActionPath, payload, cancellationToken);

        if (!TryGetProperty(root, out var actionPlanNode, "actionPlan", "action_plan"))
        {
            throw new JsonException("AI sidecar recommend_action payload is missing action_plan.");
        }

        var generatedAt = DateTimeOffset.UtcNow;
        if (TryReadTimestamp(root, out var scoredAt))
        {
            generatedAt = scoredAt;
        }

        var actions = ParseRecommendedActions(actionPlanNode);

        return new AiRecommendActionResult(
            Summary: ReadRequiredString(actionPlanNode, "summary"),
            RecommendedActions: actions,
            Prerequisites: ReadStringArray(actionPlanNode, "prerequisites"),
            Cautions: ReadStringArray(actionPlanNode, "cautions"),
            NeverAutoExecutes: ReadRequiredBoolean(actionPlanNode, "neverAutoExecutes", "never_auto_executes"),
            PolicyConstrained: ReadRequiredBoolean(actionPlanNode, "policyConstrained", "policy_constrained"),
            EvidenceBased: ReadRequiredBoolean(actionPlanNode, "evidenceBased", "evidence_based"),
            GeneratedAtUtc: generatedAt,
            RawPayload: root.Clone());
    }

    public async Task<AiHistoricalLearningResult> QueryHistoricalAsync(AiHistoricalLearningRequest request, CancellationToken cancellationToken)
    {
        var payload = new
        {
            caseId = request.CaseId,
            iocType = request.IocType,
            iocValue = request.IocValue,
            asOfTime = request.AsOfTime,
            sourceSystem = "manager",
            hostContext = request.HostContext,
            ruleContext = request.RuleContext,
            detectionPackage = request.DetectionPackage,
            topK = request.TopK,
            lookbackDays = request.LookbackDays,
        };

        var root = await PostForJsonAsync(_options.HistoricalLearningPath, payload, cancellationToken);

        var similar = new List<AiSimilarDetectionItem>();
        if (TryGetProperty(root, out var listNode, "similarDetections", "similar_detections")
            && listNode.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in listNode.EnumerateArray())
            {
                similar.Add(new AiSimilarDetectionItem(
                    DetectionId: ReadRequiredString(item, "detectionId", "detection_id"),
                    RuleFamily: ReadRequiredString(item, "ruleFamily", "rule_family"),
                    RuleId: ReadRequiredString(item, "ruleId", "rule_id"),
                    RelationType: ReadRequiredString(item, "relationType", "relation_type"),
                    ObservedAt: ReadRequiredTimestamp(item, "observedAt", "observed_at"),
                    Confidence: ReadRequiredDecimal(item, "confidence"),
                    SimilarityScore: ReadRequiredDecimal(item, "similarityScore", "similarity_score"),
                    SimilarityReasons: ReadStringArray(item, "similarityReasons", "similarity_reasons"),
                    PriorVerdicts: ReadStringArray(item, "priorVerdicts", "prior_verdicts"),
                    PriorAcceptedActions: ReadStringArray(item, "priorAcceptedActions", "prior_accepted_actions"),
                    PriorOutcomes: ReadStringArray(item, "priorOutcomes", "prior_outcomes")));
            }
        }

        return new AiHistoricalLearningResult(similar, root.Clone());
    }

    private async Task<JsonElement> PostForJsonAsync(string path, object payload, CancellationToken cancellationToken)
    {
        try
        {
            using var response = await _httpClient.PostAsJsonAsync(path, payload, JsonOptions, cancellationToken);
            var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);
            if (!response.IsSuccessStatusCode)
            {
                _logger.LogWarning(
                    "AI sidecar endpoint {Path} returned status {StatusCode}. Payload: {Body}",
                    path,
                    (int)response.StatusCode,
                    responseBody);
                throw CreateUnavailableException();
            }

            using var document = JsonDocument.Parse(responseBody);
            return document.RootElement.Clone();
        }
        catch (TaskCanceledException ex) when (!cancellationToken.IsCancellationRequested)
        {
            _logger.LogWarning(ex, "AI sidecar request timed out after {TimeoutSeconds}s for path {Path}.", _options.TimeoutSeconds, path);
            throw CreateUnavailableException(ex);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogWarning(ex, "AI sidecar transport failure for path {Path}.", path);
            throw CreateUnavailableException(ex);
        }
        catch (JsonException ex)
        {
            _logger.LogWarning(ex, "AI sidecar returned invalid JSON for path {Path}.", path);
            throw CreateUnavailableException(ex);
        }
    }

    private static object BuildScorePayload(AiScoreCaseRequest request)
    {
        return new
        {
            caseId = request.CaseId,
            iocType = request.IocType,
            iocValue = request.IocValue,
            asOfTime = request.AsOfTime,
            sourceSystem = "manager",
            hostContext = request.HostContext,
            ruleContext = request.RuleContext,
            detectionPackage = request.DetectionPackage,
        };
    }

    private static IReadOnlyList<AiDecisionProvenanceItem> ParseProvenance(JsonElement node)
    {
        if (!TryGetProperty(node, out var provenanceNode, "provenance") || provenanceNode.ValueKind != JsonValueKind.Array)
        {
            return Array.Empty<AiDecisionProvenanceItem>();
        }

        return provenanceNode.EnumerateArray().Select(item => new AiDecisionProvenanceItem(
            Source: ReadRequiredString(item, "source"),
            Key: ReadRequiredString(item, "key"),
            Value: ReadRequiredString(item, "value"),
            EvidenceId: ReadOptionalString(item, "evidenceId", "evidence_id"),
            CitationRef: ReadOptionalString(item, "citationRef", "citation_ref"))).ToArray();
    }

    private static IReadOnlyList<AiEvidenceSourceItem> ParseEvidenceSources(JsonElement decisionNode)
    {
        if (!TryGetProperty(decisionNode, out var fusionNode, "evidenceFusion", "evidence_fusion")
            || fusionNode.ValueKind != JsonValueKind.Object)
        {
            return Array.Empty<AiEvidenceSourceItem>();
        }

        var result = new List<AiEvidenceSourceItem>();
        AddEvidenceArray(result, fusionNode, "positiveEvidence", "positive_evidence");
        AddEvidenceArray(result, fusionNode, "negativeEvidence", "negative_evidence");
        AddEvidenceArray(result, fusionNode, "contradictoryEvidence", "contradictory_evidence");
        return result;
    }

    private static void AddEvidenceArray(List<AiEvidenceSourceItem> sink, JsonElement node, string camel, string snake)
    {
        if (!TryGetProperty(node, out var arrayNode, camel, snake) || arrayNode.ValueKind != JsonValueKind.Array)
        {
            return;
        }

        foreach (var item in arrayNode.EnumerateArray())
        {
            sink.Add(new AiEvidenceSourceItem(
                Channel: ReadRequiredString(item, "channel"),
                Source: ReadRequiredString(item, "source"),
                EvidenceId: ReadOptionalString(item, "evidenceId", "evidence_id"),
                Reference: ReadOptionalString(item, "reference"),
                Category: ReadRequiredString(item, "category"),
                Polarity: ReadRequiredString(item, "polarity"),
                Confidence: ReadOptionalDecimal(item, "confidence"),
                Summary: ReadRequiredString(item, "summary"),
                Anchor: ReadRequiredString(item, "anchor")));
        }
    }

    private static IReadOnlyList<AiExplanationCitation> ParseExplainCitations(JsonElement root)
    {
        if (!TryGetProperty(root, out var citationsNode, "citations") || citationsNode.ValueKind != JsonValueKind.Array)
        {
            return Array.Empty<AiExplanationCitation>();
        }

        return citationsNode.EnumerateArray().Select(item => new AiExplanationCitation(
            SourceId: ReadRequiredString(item, "sourceId", "source_id"),
            SourceType: ReadRequiredString(item, "sourceType", "source_type"),
            Snippet: ReadRequiredString(item, "snippet"),
            SourceUri: ReadOptionalString(item, "sourceUri", "source_uri"),
            StartOffset: ReadOptionalInt(item, "startOffset", "start_offset"),
            EndOffset: ReadOptionalInt(item, "endOffset", "end_offset"),
            Confidence: ReadOptionalDecimal(item, "confidence"))).ToArray();
    }

    private static IReadOnlyList<AiRecommendedActionItem> ParseRecommendedActions(JsonElement actionPlanNode)
    {
        if (!TryGetProperty(actionPlanNode, out var itemsNode, "recommendedActions", "recommended_actions")
            || itemsNode.ValueKind != JsonValueKind.Array)
        {
            return Array.Empty<AiRecommendedActionItem>();
        }

        return itemsNode.EnumerateArray().Select(item => new AiRecommendedActionItem(
            Action: ReadRequiredString(item, "action"),
            Rank: ReadOptionalInt(item, "rank") ?? 1,
            Score: ReadRequiredDecimal(item, "score"),
            Rationale: ReadRequiredString(item, "rationale"),
            Prerequisites: ReadStringArray(item, "prerequisites"),
            Cautions: ReadStringArray(item, "cautions"),
            EscalationTarget: ReadRequiredString(item, "escalationTarget", "escalation_target"),
            RequiredReviewerRole: ReadRequiredString(item, "requiredReviewerRole", "required_reviewer_role"),
            RequiresHumanApproval: ReadRequiredBoolean(item, "requiresHumanApproval", "requires_human_approval"),
            ExecutionMode: ReadRequiredString(item, "executionMode", "execution_mode"))).ToArray();
    }

    private static IReadOnlyList<string> ReadStringArray(JsonElement node, params string[] propertyNames)
    {
        if (!TryGetProperty(node, out var arrayNode, propertyNames) || arrayNode.ValueKind != JsonValueKind.Array)
        {
            return Array.Empty<string>();
        }

        return arrayNode
            .EnumerateArray()
            .Where(x => x.ValueKind == JsonValueKind.String)
            .Select(x => x.GetString())
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x!.Trim())
            .ToArray();
    }

    private static string ReadRequiredString(JsonElement node, params string[] propertyNames)
    {
        if (!TryGetProperty(node, out var value, propertyNames) || value.ValueKind != JsonValueKind.String)
        {
            throw new JsonException($"Missing required string field '{propertyNames[0]}'.");
        }

        var text = value.GetString();
        if (string.IsNullOrWhiteSpace(text))
        {
            throw new JsonException($"Field '{propertyNames[0]}' cannot be empty.");
        }

        return text.Trim();
    }

    private static string? ReadOptionalString(JsonElement node, params string[] propertyNames)
    {
        if (!TryGetProperty(node, out var value, propertyNames) || value.ValueKind == JsonValueKind.Null)
        {
            return null;
        }

        if (value.ValueKind != JsonValueKind.String)
        {
            return null;
        }

        var text = value.GetString();
        return string.IsNullOrWhiteSpace(text) ? null : text.Trim();
    }

    private static decimal ReadRequiredDecimal(JsonElement node, params string[] propertyNames)
    {
        if (!TryGetProperty(node, out var value, propertyNames) || value.ValueKind != JsonValueKind.Number)
        {
            throw new JsonException($"Missing required number field '{propertyNames[0]}'.");
        }

        return value.GetDecimal();
    }

    private static decimal? ReadOptionalDecimal(JsonElement node, params string[] propertyNames)
    {
        if (!TryGetProperty(node, out var value, propertyNames) || value.ValueKind == JsonValueKind.Null)
        {
            return null;
        }

        return value.ValueKind == JsonValueKind.Number
            ? value.GetDecimal()
            : null;
    }

    private static bool ReadRequiredBoolean(JsonElement node, params string[] propertyNames)
    {
        if (!TryGetProperty(node, out var value, propertyNames)
            || (value.ValueKind is not JsonValueKind.True and not JsonValueKind.False))
        {
            throw new JsonException($"Missing required boolean field '{propertyNames[0]}'.");
        }

        return value.GetBoolean();
    }

    private static int? ReadOptionalInt(JsonElement node, params string[] propertyNames)
    {
        if (!TryGetProperty(node, out var value, propertyNames) || value.ValueKind == JsonValueKind.Null)
        {
            return null;
        }

        return value.ValueKind == JsonValueKind.Number
            ? value.GetInt32()
            : null;
    }

    private static DateTimeOffset ReadRequiredTimestamp(JsonElement node, params string[] propertyNames)
    {
        var raw = ReadRequiredString(node, propertyNames);
        if (!DateTimeOffset.TryParse(raw, out var parsed))
        {
            throw new JsonException($"Field '{propertyNames[0]}' must be a valid timestamp.");
        }

        return parsed;
    }

    private static bool TryReadTimestamp(JsonElement node, out DateTimeOffset value)
    {
        foreach (var name in new[] { "scoredAtUtc", "scored_at_utc", "generatedAtUtc", "generated_at_utc", "processedAt", "processed_at" })
        {
            if (TryGetProperty(node, out var item, name)
                && item.ValueKind == JsonValueKind.String
                && DateTimeOffset.TryParse(item.GetString(), out var parsed))
            {
                value = parsed;
                return true;
            }
        }

        value = default;
        return false;
    }

    private static bool TryGetProperty(JsonElement node, out JsonElement value, params string[] propertyNames)
    {
        foreach (var propertyName in propertyNames)
        {
            if (node.ValueKind == JsonValueKind.Object && node.TryGetProperty(propertyName, out value))
            {
                return true;
            }
        }

        value = default;
        return false;
    }

    private static OptionalDependencyUnavailableException CreateUnavailableException(Exception? innerException = null)
    {
        return new OptionalDependencyUnavailableException(
            dependencyName: SidecarDependencyName,
            condition: TemporaryUnavailableCondition,
            message: SafeUnavailableMessage,
            innerException: innerException);
    }
}
