<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AccountController.cs" />
    <Compile Remove="Controllers\ApiTestController.cs" />
    <Compile Remove="Controllers\HomeController.cs" />
    <Compile Remove="Controllers\IOCManagerController.cs" />
    <Compile Remove="Models\**\*.cs" />
    <Compile Remove="Views\**\*.cshtml.cs" />
    <RazorGenerate Remove="Views\**\*.cshtml" />
    <Content Remove="Views\**\*" />
    <None Remove="Views\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.12" />
  </ItemGroup>

</Project>
