namespace IocVmwareIngestion.Api.Models;

public sealed class IocFileModel
{
    // The file ID is a unique identifier for the file, which can be used to reference the file in other parts of the application. It is typically generated by the database when the file is added to the system.
    public int FileId { get; init; }
    public string Name { get; init; } = string.Empty;
    public string FilePath { get; init; } = string.Empty;
    public string? FileHash { get; init; }
    public int RelatedIocCount { get; init; }
}
