from __future__ import annotations

import json
import re
from collections import Counter
from datetime import datetime
from typing import Any
from urllib import error, request as urllib_request

from .config import ServiceSettings
from .contracts import (
    ScanAnalystAlertInput,
    ScanAnalystJobInput,
    ScanAnalystManagedServerInput,
    ScanAnalystRequest,
    ScanAnalystResponse,
    ScanAnalystRuleInput,
    ScanAnalystRuleResponse,
    ScanAnalystPlanProposalResponse,
    ScanAnalystScannerCapability,
    ScanAnalystTargetResponse,
    ScanAnalystTriggerInput,
)

_TOKEN_RE = re.compile(r"[a-z0-9]{3,}")
_SCANNER_ORDER: tuple[ScanAnalystScannerCapability, ...] = ("Yara", "Sigma", "Snort", "Suricata")
_SCANNER_KEYWORDS: dict[ScanAnalystScannerCapability, tuple[str, ...]] = {
    "Yara": ("yara", "file", "files", "binary", "malware", "artifact", "hash", "dropper"),
    "Sigma": ("sigma", "windows", "event", "events", "log", "logs", "powershell", "evtx", "script"),
    "Snort": ("snort", "network", "traffic", "packet", "packets", "pcap", "beacon"),
    "Suricata": ("suricata", "network", "traffic", "packet", "packets", "pcap", "http"),
}
_SEVERITY_WEIGHT = {"critical": 5.0, "high": 4.0, "medium": 2.5, "low": 1.0}


def recommend_scan_plan(request: ScanAnalystRequest, settings: ServiceSettings | None = None) -> ScanAnalystResponse:
    heuristic = _recommend_with_heuristics(request)
    if settings and settings.openai_api_key:
        try:
            return _recommend_with_openai(request, heuristic, settings)
        except Exception:
            if request.allow_local_planner:
                return heuristic.model_copy(
                    update={
                        "planner_mode": "local",
                        "observations": [
                            *heuristic.observations,
                            "OpenAI planner was configured but unavailable; local planner was used because the request explicitly allowed it.",
                        ]
                    }
                )
            raise

    if request.allow_local_planner:
        return heuristic

    raise RuntimeError(
        "OpenAI planner is required for Zira scan-analysis requests. "
        "Configure OPENAI_API_KEY or explicitly allow the local planner in the request."
    )


def _recommend_with_heuristics(request: ScanAnalystRequest) -> ScanAnalystResponse:
    selected_scanner = request.preferred_scanner_capability or _choose_scanner(request)
    selected_targets, target_warnings = _choose_targets(request, selected_scanner)
    selected_rules, rule_selection_mode, rule_scope_type, rule_scope_value, rule_warnings = _choose_rules(
        request,
        selected_scanner,
        selected_targets,
    )

    focus_label = request.focus_subnet.name if request.focus_subnet else "server inventory"
    plan_name = _build_plan_name(request.objective, selected_scanner, focus_label)
    description = f"AI analyst proposal for {focus_label}. Objective: {request.objective.strip()}"
    trigger_summary = ", ".join(trigger.trigger_label for trigger in request.active_triggers[:3]) or "operator request"
    operator_notes = (
        "Generated by Zira using live discovery, inventory, alert, and execution posture. "
        f"Focus: {focus_label}. Trigger context: {trigger_summary}. Objective: {request.objective.strip()}"
    )

    observations = _build_observations(request, selected_scanner, selected_targets, selected_rules)
    reasoning = _build_reasoning(request, selected_scanner, selected_targets, selected_rules, rule_selection_mode)
    validation_warnings = [*target_warnings, *rule_warnings]

    proposal = ScanAnalystPlanProposalResponse(
        name=plan_name,
        description=description,
        scanner_capability=selected_scanner,
        rule_selection_mode=rule_selection_mode,
        rule_scope_type=rule_scope_type,
        rule_scope_value=rule_scope_value,
        cadence_type="Manual",
        operator_notes=operator_notes,
        status="Draft",
        target_server_ids=[item.target_server_id for item in selected_targets],
        rule_revision_ids=[item.rule_revision_id for item in selected_rules],
        targets=selected_targets,
        rules=selected_rules,
    )

    return ScanAnalystResponse(
        summary=(
            f"Prepared a {selected_scanner} scan proposal for {len(selected_targets)} target"
            f"{'' if len(selected_targets) == 1 else 's'} with "
            f"{'explicit rules' if rule_selection_mode == 'RuleSet' else 'scope-based rule selection'}."
        ),
        planner_mode="local",
        observations=observations,
        reasoning=reasoning,
        validation_warnings=validation_warnings,
        recommended_scanner_capability=selected_scanner,
        proposal=proposal,
    )


def _choose_scanner(request: ScanAnalystRequest) -> ScanAnalystScannerCapability:
    objective = request.objective.lower()
    scores: Counter[str] = Counter()
    for scanner, keywords in _SCANNER_KEYWORDS.items():
        for keyword in keywords:
            if keyword in objective:
                scores[scanner] += 3

    for trigger in request.active_triggers:
        if trigger.scanner_capability:
            scores[trigger.scanner_capability] += _severity_multiplier(trigger.severity) * 1.5
        scores.update(_score_text_for_scanners(f"{trigger.trigger_label} {trigger.summary}", weight=1.2))

    for alert in request.recent_alerts:
        if alert.suggested_scanner_capability:
            scores[alert.suggested_scanner_capability] += _severity_multiplier(alert.severity) * 2.0
        scores.update(_score_text_for_scanners(f"{alert.title} {alert.summary} {alert.rule_name}", weight=1.0))

    for server in request.managed_servers:
        capabilities = {item.lower() for item in server.scanner_capabilities}
        for scanner in _SCANNER_ORDER:
            if scanner.lower() in capabilities:
                scores[scanner] += 1.0

        os_label = server.operating_system.lower()
        if "windows" in os_label:
            scores["Sigma"] += 1.0
        if "linux" in os_label or "server" in os_label:
            scores["Yara"] += 0.8

    for fact in request.external_server_facts:
        if fact.preferred_scanner_connectivity and fact.preferred_scanner_connectivity.lower() == "online":
            for capability in fact.healthy_scanner_capabilities:
                normalized = _normalize_scanner_name(capability)
                if normalized:
                    scores[normalized] += 1.4

    return max(_SCANNER_ORDER, key=lambda scanner: (scores[scanner], -_SCANNER_ORDER.index(scanner)))


def _choose_targets(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
) -> tuple[list[ScanAnalystTargetResponse], list[str]]:
    ranked: list[tuple[float, ScanAnalystManagedServerInput]] = []
    warnings: list[str] = []
    objective = request.objective.lower()
    target_bias = _build_target_bias(request)
    server_facts = {fact.target_server_id: fact for fact in request.external_server_facts}

    for server in request.managed_servers:
        score = 0.0
        if request.focus_subnet and server.subnet_id == request.focus_subnet.subnet_id:
            score += 4.0
        if server.connectivity_status.lower() == "online":
            score += 3.0
        elif server.connectivity_status.lower() == "degraded":
            score += 1.5
        if server.status.lower() == "active":
            score += 2.0
        if scanner.lower() in {item.lower() for item in server.scanner_capabilities}:
            score += 2.5
        if server.environment and server.environment.lower() in objective:
            score += 1.5
        if server.hostname.lower() in objective or server.ip_address in objective:
            score += 3.0
        if "windows" in objective and "windows" in server.operating_system.lower():
            score += 2.0
        if "linux" in objective and "linux" in server.operating_system.lower():
            score += 2.0
        score += target_bias.get(server.target_server_id, 0.0)

        fact = server_facts.get(server.target_server_id)
        if fact:
            if fact.has_remote_connection_metadata:
                score += 1.2
            if scanner in (_normalize_scanner_name(value) for value in fact.healthy_scanner_capabilities):
                score += 1.5
            if fact.preferred_scanner_connectivity and fact.preferred_scanner_connectivity.lower() == "degraded":
                score -= 0.75

        ranked.append((score, server))

    ranked.sort(key=lambda item: (item[0], item[1].hostname.lower()), reverse=True)
    selected = [
        server
        for score, server in ranked[: request.max_target_count]
        if score > 0 or len(ranked) <= request.max_target_count
    ]
    if not selected:
        selected = [item for _, item in ranked[: request.max_target_count]]

    output: list[ScanAnalystTargetResponse] = []
    for server in selected:
        reason_bits: list[str] = []
        if request.focus_subnet and server.subnet_id == request.focus_subnet.subnet_id:
            reason_bits.append("belongs to the focused subnet")
        if server.connectivity_status.lower() == "online":
            reason_bits.append("currently online")
        elif server.connectivity_status.lower() == "degraded":
            reason_bits.append("still reachable despite degraded coverage")
        if scanner.lower() in {item.lower() for item in server.scanner_capabilities}:
            reason_bits.append(f"already advertises {scanner} coverage")
        else:
            warnings.append(
                f"{server.hostname} does not currently advertise {scanner}; the plan may rely on connector fallback."
            )

        fact = server_facts.get(server.target_server_id)
        if fact and fact.has_remote_connection_metadata:
            reason_bits.append("has remote connection metadata for precise follow-up")
        if target_bias.get(server.target_server_id, 0.0) >= 4.0:
            reason_bits.append("was directly implicated by a recent trigger or alert")
        if not reason_bits:
            reason_bits.append("ranked as the best available analyst candidate")

        output.append(
            ScanAnalystTargetResponse(
                target_server_id=server.target_server_id,
                hostname=server.hostname,
                ip_address=server.ip_address,
                operating_system=server.operating_system,
                environment=server.environment,
                status=server.status,
                connectivity_status=server.connectivity_status,
                scanner_capabilities=server.scanner_capabilities,
                reason=", ".join(reason_bits),
            )
        )

    return output, list(dict.fromkeys(warnings))


def _choose_rules(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
    selected_targets: list[ScanAnalystTargetResponse],
) -> tuple[list[ScanAnalystRuleResponse], str, str | None, str | None, list[str]]:
    candidate_rules = [rule for rule in request.candidate_rules if rule.rule_family.lower() == scanner.lower()]
    warnings: list[str] = []
    if not candidate_rules:
        return [], "RuleScope", _fallback_scope_type(request), _fallback_scope_value(request), [
            f"No active {scanner} rules were available; using scope-based selection."
        ]

    tokens = set(_TOKEN_RE.findall(request.objective.lower()))
    alert_tokens = set(
        token
        for alert in request.recent_alerts
        for token in _TOKEN_RE.findall(f"{alert.title} {alert.summary} {alert.rule_name}".lower())
    )
    target_environments = {target.environment.lower() for target in selected_targets if target.environment}
    ranked: list[tuple[float, ScanAnalystRuleInput]] = []
    for rule in candidate_rules:
        searchable = " ".join(
            filter(
                None,
                [
                    rule.rule_name,
                    rule.description,
                    rule.scope_type,
                    rule.scope_value or "",
                    rule.lifecycle_status,
                ],
            )
        ).lower()
        rule_tokens = set(_TOKEN_RE.findall(searchable))
        overlap = len(tokens.intersection(rule_tokens))
        alert_overlap = len(alert_tokens.intersection(rule_tokens))
        score = float(overlap * 3 + alert_overlap * 4 + rule.revision_number)
        if request.focus_subnet and rule.scope_type.lower() == "subnet" and rule.scope_value == request.focus_subnet.subnet_id:
            score += 2.0
        if rule.scope_type.lower() == "environment" and rule.scope_value and rule.scope_value.lower() in target_environments:
            score += 1.5
        if any(alert.rule_name.lower() == rule.rule_name.lower() for alert in request.recent_alerts):
            score += 3.0
        ranked.append((score, rule))

    ranked.sort(key=lambda item: (item[0], item[1].revision_number, item[1].rule_name.lower()), reverse=True)
    selected_rows = [rule for score, rule in ranked[:5] if score > 0]

    if not selected_rows:
        warnings.append("No high-signal rule matches were found; falling back to scoped rule selection.")
        return [], "RuleScope", _fallback_scope_type(request), _fallback_scope_value(request), warnings

    return (
        [
            ScanAnalystRuleResponse(
                rule_revision_id=rule.rule_revision_id,
                rule_artifact_id=rule.rule_artifact_id,
                rule_name=rule.rule_name,
                rule_family=rule.rule_family,
                revision_number=rule.revision_number,
                version_label=rule.version_label,
                lifecycle_status=rule.lifecycle_status,
                scope_type=rule.scope_type,
                scope_value=rule.scope_value,
                reason="matched the objective, recent trigger context, and current rule coverage.",
            )
            for rule in selected_rows
        ],
        "RuleSet",
        None,
        None,
        warnings,
    )


def _build_observations(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
    targets: list[ScanAnalystTargetResponse],
    rules: list[ScanAnalystRuleResponse],
) -> list[str]:
    observations = [
        f"Evaluated {len(request.discovery_runs)} discovery runs, {len(request.discovered_hosts)} discovered hosts, and {len(request.managed_servers)} managed servers.",
        f"Selected {scanner} based on the objective wording, live triggers, and available scanner coverage.",
        f"Prepared {len(targets)} target candidate{'s' if len(targets) != 1 else ''} and {len(rules)} explicit rule candidate{'s' if len(rules) != 1 else ''}.",
    ]
    if request.recent_alerts:
        latest_alert = request.recent_alerts[0]
        observations.append(
            f"Recent alerts contributed {len(request.recent_alerts)} live signal{'s' if len(request.recent_alerts) != 1 else ''}; the newest was {latest_alert.severity} on {latest_alert.target_display}."
        )
    if request.active_triggers:
        observations.append(
            f"Autonomy trigger context included {len(request.active_triggers)} indicator{'s' if len(request.active_triggers) != 1 else ''}."
        )
    if request.external_server_facts:
        remote_ready = sum(1 for fact in request.external_server_facts if fact.has_remote_connection_metadata)
        observations.append(
            f"Remote execution facts were available for {remote_ready} of {len(request.external_server_facts)} managed targets."
        )
    if request.recent_jobs:
        latest_job = request.recent_jobs[0]
        observations.append(
            f"Most recent observed job status was {latest_job.status} with {latest_job.detection_count} detections."
        )
    return observations


def _build_reasoning(
    request: ScanAnalystRequest,
    scanner: ScanAnalystScannerCapability,
    targets: list[ScanAnalystTargetResponse],
    rules: list[ScanAnalystRuleResponse],
    rule_selection_mode: str,
) -> list[str]:
    reasoning = [
        f"{scanner} is the best fit for the requested objective given the current alerts, triggers, and live infrastructure context.",
        "Targets were prioritized by trigger relevance, subnet focus, live connectivity, and scanner alignment.",
    ]
    if request.recent_alerts:
        reasoning.append("Recent alerts were treated as first-class task indicators, so implicated hosts were biased upward.")
    if request.external_server_facts:
        reasoning.append("External server facts were used to prefer hosts with healthy scanner posture and real remote access metadata.")
    if rule_selection_mode == "RuleSet":
        reasoning.append("A compact RuleSet was chosen so the execution plan stays bounded and reviewable.")
    else:
        reasoning.append("RuleScope mode was chosen because the trigger context was broader than the current explicit rule matches.")
    if request.focus_subnet:
        reasoning.append(f"The proposal is anchored to subnet {request.focus_subnet.name} ({request.focus_subnet.cidr_block}).")
    if targets and any(not target.scanner_capabilities for target in targets):
        reasoning.append("Some selected targets have limited advertised scanner coverage, so fallback execution paths may be required.")
    if not rules:
        reasoning.append("The proposal intentionally avoids hard-coding rule revisions until better keyword alignment is available.")
    return reasoning


def _build_target_bias(request: ScanAnalystRequest) -> dict[str, float]:
    bias: Counter[str] = Counter()
    for alert in request.recent_alerts:
        if alert.matched_target_server_id:
            bias[alert.matched_target_server_id] += _severity_multiplier(alert.severity) * 2.0
    for trigger in request.active_triggers:
        if trigger.target_server_id:
            bias[trigger.target_server_id] += _severity_multiplier(trigger.severity) * 2.0
    return dict(bias)


def _fallback_scope_type(request: ScanAnalystRequest) -> str:
    return "Subnet" if request.focus_subnet else "Global"


def _fallback_scope_value(request: ScanAnalystRequest) -> str | None:
    return request.focus_subnet.subnet_id if request.focus_subnet else None


def _score_text_for_scanners(text: str, weight: float) -> Counter[str]:
    lowered = text.lower()
    scores: Counter[str] = Counter()
    for scanner, keywords in _SCANNER_KEYWORDS.items():
        for keyword in keywords:
            if keyword in lowered:
                scores[scanner] += weight
    return scores


def _normalize_scanner_name(value: str | None) -> ScanAnalystScannerCapability | None:
    if not value:
        return None
    lowered = value.strip().lower()
    for scanner in _SCANNER_ORDER:
        if scanner.lower() in lowered:
            return scanner
    return None


def _severity_multiplier(value: str | None) -> float:
    if not value:
        return 1.0
    return _SEVERITY_WEIGHT.get(value.strip().lower(), 1.0)


def _build_plan_name(objective: str, scanner: ScanAnalystScannerCapability, focus_label: str) -> str:
    tokens = _TOKEN_RE.findall(objective.lower())
    objective_label = "-".join(tokens[:4]) or "analyst-objective"
    focus = re.sub(r"[^a-z0-9]+", "-", focus_label.lower()).strip("-") or "fleet"
    return f"{scanner.lower()}-{focus}-{objective_label}"[:96]


def _recommend_with_openai(
    request: ScanAnalystRequest,
    heuristic: ScanAnalystResponse,
    settings: ServiceSettings,
) -> ScanAnalystResponse:
    payload = {
        "objective": request.objective,
        "action": request.action,
        "preferredScannerCapability": request.preferred_scanner_capability,
        "maxTargetCount": request.max_target_count,
        "focusSubnet": request.focus_subnet.model_dump(mode="json", by_alias=True) if request.focus_subnet else None,
        "activeTriggers": [item.model_dump(mode="json", by_alias=True) for item in request.active_triggers[:6]],
        "recentAlerts": [item.model_dump(mode="json", by_alias=True) for item in request.recent_alerts[:8]],
        "managedServers": [item.model_dump(mode="json", by_alias=True) for item in request.managed_servers[:12]],
        "externalServerFacts": [item.model_dump(mode="json", by_alias=True) for item in request.external_server_facts[:12]],
        "candidateRules": [item.model_dump(mode="json", by_alias=True) for item in request.candidate_rules[:16]],
        "recentJobs": [item.model_dump(mode="json", by_alias=True) for item in request.recent_jobs[:8]],
        "heuristicDraft": heuristic.model_dump(mode="json", by_alias=True),
    }

    schema = {
        "name": "scan_analyst_response",
        "schema": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "summary": {"type": "string"},
                "observations": {"type": "array", "items": {"type": "string"}},
                "reasoning": {"type": "array", "items": {"type": "string"}},
                "validationWarnings": {"type": "array", "items": {"type": "string"}},
                "recommendedScannerCapability": {"type": "string", "enum": list(_SCANNER_ORDER)},
                "proposal": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "name": {"type": "string"},
                        "description": {"type": "string"},
                        "scannerCapability": {"type": "string", "enum": list(_SCANNER_ORDER)},
                        "ruleSelectionMode": {"type": "string", "enum": ["RuleSet", "RuleScope"]},
                        "ruleScopeType": {"type": ["string", "null"]},
                        "ruleScopeValue": {"type": ["string", "null"]},
                        "cadenceType": {"type": "string", "enum": ["Manual", "Interval", "Daily", "Weekly"]},
                        "intervalMinutes": {"type": ["integer", "null"]},
                        "runAtHourUtc": {"type": ["integer", "null"]},
                        "runAtMinuteUtc": {"type": ["integer", "null"]},
                        "weeklyDayOfWeek": {"type": ["integer", "null"]},
                        "operatorNotes": {"type": "string"},
                        "status": {"type": "string"},
                        "targetServerIds": {"type": "array", "items": {"type": "string"}},
                        "ruleRevisionIds": {"type": "array", "items": {"type": "string"}},
                        "targets": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": False,
                                "properties": {
                                    "targetServerId": {"type": "string"},
                                    "hostname": {"type": "string"},
                                    "ipAddress": {"type": "string"},
                                    "operatingSystem": {"type": "string"},
                                    "environment": {"type": "string"},
                                    "status": {"type": "string"},
                                    "connectivityStatus": {"type": "string"},
                                    "scannerCapabilities": {"type": "array", "items": {"type": "string"}},
                                    "reason": {"type": "string"},
                                },
                                "required": [
                                    "targetServerId",
                                    "hostname",
                                    "ipAddress",
                                    "operatingSystem",
                                    "environment",
                                    "status",
                                    "connectivityStatus",
                                    "scannerCapabilities",
                                    "reason",
                                ],
                            },
                        },
                        "rules": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": False,
                                "properties": {
                                    "ruleRevisionId": {"type": "string"},
                                    "ruleArtifactId": {"type": "string"},
                                    "ruleName": {"type": "string"},
                                    "ruleFamily": {"type": "string"},
                                    "revisionNumber": {"type": "integer"},
                                    "versionLabel": {"type": "string"},
                                    "lifecycleStatus": {"type": "string"},
                                    "scopeType": {"type": "string"},
                                    "scopeValue": {"type": ["string", "null"]},
                                    "reason": {"type": "string"},
                                },
                                "required": [
                                    "ruleRevisionId",
                                    "ruleArtifactId",
                                    "ruleName",
                                    "ruleFamily",
                                    "revisionNumber",
                                    "versionLabel",
                                    "lifecycleStatus",
                                    "scopeType",
                                    "scopeValue",
                                    "reason",
                                ],
                            },
                        },
                    },
                    "required": [
                        "name",
                        "description",
                        "scannerCapability",
                        "ruleSelectionMode",
                        "ruleScopeType",
                        "ruleScopeValue",
                        "cadenceType",
                        "intervalMinutes",
                        "runAtHourUtc",
                        "runAtMinuteUtc",
                        "weeklyDayOfWeek",
                        "operatorNotes",
                        "status",
                        "targetServerIds",
                        "ruleRevisionIds",
                        "targets",
                        "rules",
                    ],
                },
            },
            "required": [
                "summary",
                "observations",
                "reasoning",
                "validationWarnings",
                "recommendedScannerCapability",
                "proposal",
            ],
        },
    }

    system_prompt = (
        "You are Zira, a bounded cybersecurity scan-planning copilot. "
        "Use the provided live context, recent alerts, server facts, and heuristic draft to improve the plan. "
        "Return only valid JSON that matches the schema. Keep proposals safe, compact, and reviewable. "
        "Never invent server ids or rule ids not present in the payload."
    )
    response_body = _post_openai_responses_request(
        settings,
        {
            "model": settings.openai_planner_model,
            "input": [
                {
                    "role": "system",
                    "content": [{"type": "input_text", "text": system_prompt}],
                },
                {
                    "role": "user",
                    "content": [{"type": "input_text", "text": json.dumps(payload, separators=(",", ":"))}],
                },
            ],
            "text": {
                "format": {
                    "type": "json_schema",
                    "name": schema["name"],
                    "schema": schema["schema"],
                    "strict": True,
                }
            },
        },
    )
    output_text = _extract_response_output_text(response_body)
    if not isinstance(output_text, str) or not output_text.strip():
        raise ValueError("OpenAI response did not include output_text.")

    parsed = ScanAnalystResponse.model_validate_json(output_text)
    return parsed.model_copy(
        update={
            "planner_mode": "openai_refined",
            "observations": [
                *parsed.observations,
                f"OpenAI planner model {settings.openai_planner_model} refined the bounded Zira draft.",
            ]
        }
    )


def _post_openai_responses_request(settings: ServiceSettings, payload: dict[str, Any]) -> dict[str, Any]:
    body = json.dumps(payload).encode("utf-8")
    request_obj = urllib_request.Request(
        url=f"{settings.openai_base_url}/responses",
        data=body,
        headers={
            "Authorization": f"Bearer {settings.openai_api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib_request.urlopen(request_obj, timeout=settings.openai_timeout_seconds) as response:
            return json.loads(response.read().decode("utf-8"))
    except error.HTTPError as exc:  # pragma: no cover - exercised only with remote API configured
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"OpenAI planner request failed with status {exc.code}: {detail}") from exc
    except error.URLError as exc:  # pragma: no cover - exercised only with remote API configured
        raise RuntimeError(f"OpenAI planner transport failed: {exc.reason}") from exc


def _extract_response_output_text(response_body: dict[str, Any]) -> str | None:
    output_text = response_body.get("output_text")
    if isinstance(output_text, str) and output_text.strip():
        return output_text

    for output_item in response_body.get("output") or []:
        if not isinstance(output_item, dict):
            continue
        for content_item in output_item.get("content") or []:
            if not isinstance(content_item, dict):
                continue
            if content_item.get("type") == "output_text" and isinstance(content_item.get("text"), str):
                return content_item["text"]

    return None
